name: Jefferson - Extractta Test

on: [push]
jobs:
  cypress-run:
   strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true # Runs test in parallel using settings above
    name: Run Cypress tests
    runs-on: ubuntu-latest
      - name: Install dependencies ⌛
        run: npm ci
        env:

          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: cypress-videos
          path: cypress/videos
