name: AGI - Testing - Blog
on:
  push:
jobs:
  cypress-run:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    timeout-minutes: 30
    steps:
      - name: Checkout ✔️
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies ⌛
        run: npm ci

      - name: Cypress run 🚀
        uses: cypress-io/github-action@v4
        with:
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: cypress-videos
          path: cypress/videos
